---

- name: Install Java 8 using YUM.
  yum:
    name: "{{ java.VERSION }}"
    state: present
  become: true

- name: Correct the alternatives to change default Java version.
  alternatives:
    name: java
    link: /usr/bin/java
    path: "{{ java.ALTERNATIVES }}"
...
